name: Build

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to AWS - Dev
    uses: ./.github/workflows/deploy-aws.yml
    with:
      environment: dev
  # deploy-uat:
  #   name: Deploy to AWS - UAT
  #   runs-on: "ubuntu-latest"
  #   environment: "uat"
  #   needs: [deploy-dev]
  #   uses: ./.github/workflows/deploy-aws.yml
  #   with:
  #     environment: uat
  # deploy-prod:
  #   name: Deploy to AWS - Prod
  #   runs-on: "ubuntu-latest"
  #   environment: "prod"
  #   needs: [deploy-dev, deploy-uat]
  #   uses: ./.github/workflows/deploy-aws.yml
  #   with:
  #     environment: prod
