name: Deploy to AWS

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      AWS_ECS_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
      ECS_CLUSTER:
        required: true
      ECS_SERVICE:
        required: true

# Request permissions to be able to access the Github OIDC JWT,
# which is needed for AWS actions.
permissions:
  id-token: write   # This is required for requesting a JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy to AWS - ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      appTaskDefinitionFile: ./aws/${{ inputs.environment }}/ecs/task_definitions/uesio_web.json
      workerTaskDefinitionFile: ./aws/${{ inputs.environment }}/ecs/task_definitions/uesio_worker.json
      appSpecFile: ./aws/${{ inputs.environment }}/ecs/task_definitions/appspec.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ECS_ROLE_ARN }}
          role-session-name: ecsdeploy
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy ECS task definition - worker
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.11
        with:
          wait-for-minutes: 5
          task-definition: ${{ env.workerTaskDefinitionFile }}
          service: tcm-uesio-${{ inputs.environment }}-ecs-service-Worker
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
      - name: Deploy ECS task definition - app
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.11
        with:
          codedeploy-appspec: ${{ env.appSpecFile }}
          codedeploy-application: tcm-uesio-${{ inputs.environment }}-uesio-${{ inputs.environment }}
          codedeploy-deployment-group: tcm-uesio-${{ inputs.environment }}-uesio-${{ inputs.environment }}
          wait-for-minutes: 5
          task-definition: ${{ env.appTaskDefinitionFile }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
