name: Manual Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        default: "prod"
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    name: Deploy to AWS - ${{ inputs.environment }}
    uses: ./.github/workflows/deploy-aws.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
