name: Scale ECS tasks up for peak hours

on:
  schedule:
    # - cron: "0 6 * * 1,2,3,4,5"
    - cron: "0 17 * * 1,2,3,4,5"

jobs:
  scale-up-dev:
    secrets: inherit
    name: Scale UP ECS cluster - Dev
    uses: ./.github/workflows/scale-ecs.yml
    with:
      environment: dev
      appTaskDesiredCount: 1
      workerTaskDesiredCount: 1
        
