name: Scale ECS tasks up for peak hours

on:
  workflow_dispatch:
  # schedule:
    # Schedule for 8:48 AM Switzerland time. Github recommends that you 
    # NOT schedule at common times like top of the hour, etc. to avoid delays.
    # - cron: "48 6 * * 1,2,3,4,5"

jobs:
  scale-up-dev:
    secrets: inherit
    name: Scale UP ECS cluster - Dev
    uses: ./.github/workflows/scale-ecs.yml
    with:
      environment: dev
      appTaskDesiredCount: 1
      workerTaskDesiredCount: 1
        
