name: Scale ECS tasks down during off-peak hours

on:
  workflow_dispatch:
  # schedule:
    # Schedule for 5:39 Eastern time. Github recommends that you 
    # NOT schedule at common times like top of the hour, etc. to avoid delays.
    # - cron: "39 21 * * 1,2,3,4,5"

jobs:
  scale-down-dev:
    secrets: inherit
    name: Scale DOWN ECS cluster - Dev
    uses: ./.github/workflows/scale-ecs.yml
    with:
      environment: dev
      appTaskDesiredCount: 0
      workerTaskDesiredCount: 0
      