name: Run Platform Command

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod
      command:
        description: "Command"
        type: choice
        required: true
        default: migrate
        options:
          - migrate
          - seed
      command_args:
        description: "Command arguments (optional)"
        type: string

# Request permissions to be able to access the Github OIDC JWT,
# which is needed for AWS actions.
permissions:
  id-token: write   # This is required for requesting a JWT

jobs:
  migrate:
    name: Execute migrations
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ECS_ROLE_ARN }}
          role-session-name: gh_platform_command_${{ inputs.command }}
          aws-region: ${{ secrets.AWS_REGION }}    
      - name: Run ${{ inputs.command }}
        uses: geekcell/github-action-aws-ecs-run-task@v5
        with:
          cluster: ${{ secrets.ECS_CLUSTER }}
          task-definition: uesio_worker
          # subnet-ids: |
          #   subnet-0bbe0ce0cd49f3cf5
          #   subnet-0d9cbac1e23d41596
          #security-group-ids: |
          #  sg-0bb1caf92dfc04798
          subnet-ids: |
            ${{ vars.ECS_SN_ID }}
          security-group-ids: |
            ${{ vars.ECS_SG_ID }} 
          override-container: uesio_worker
          override-container-command: |
            /bin/sh
            -c
            ./uesio ${{ inputs.command }} ${{ inputs.command_args }}

