name: Update UAT / PROD Docker image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to update"
        required: true
        default: "uat"
        type: choice
        options:
          - uat
          - prod

jobs:
  deploy:
    name: "Update Docker image for ECS task def for: ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update Docker image
        env:
          targetEnv: ${{ inputs.environment }}
        run: bash scripts/update-env-image.sh
      
