name: Promote DEV/UAT Docker image to UAT/PROD

on:
  workflow_dispatch:
    inputs:
      sourceEnv:
        description: "Source environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
      targetEnv:
        description: "Target environment to update"
        required: true
        default: "uat"
        type: choice
        options:
          - uat
          - prod

jobs:
  update-image:
    name: "Update Docker image"
    runs-on: ubuntu-latest
    environment: ${{ inputs.sourceEnv }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Docker image
        env:
          sourceEnv: ${{ inputs.sourceEnv }}
          targetEnv: ${{ inputs.targetEnv }}
          gitUsername: ${{ github.actor }}
        run: bash scripts/update-env-image.sh
  deploy:
    name: Deploy to AWS - ${{ inputs.targetEnv }}
    needs: update-image
    uses: ./.github/workflows/deploy-aws.yml
    with:
      environment: ${{ inputs.targetEnv }}
    secrets: inherit
      
